[package]
name = "facet-owned-shape"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = "0.32.2"
facet-core = "0.32.2"
facet-reflect = "0.32.2"
facet-shapelike = "0.32.2"
facet-diff = "0.32.2"
sea-query = { version = "0.32.7", default-features = false }
